api:
  autodiscoveryId: "18690899"  

http:
 listener:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
 request:
  host: "sb-salesdoc-papi.us-e1.cloudhub.io"
  timeout: "30000"
  port: ""
  path: "/api/salesdoc_output"
  
https:
  host: "0.0.0.0"
  port: "8082"